import PageHeader from "@/components/PageHeader";

export const metadata = {
  title: "Terms of Service — StudyZone AI",
  description: "Terms of Service for StudyZone AI.",
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-3xl px-6 pb-20">
        <PageHeader title="Terms of Service" />

        <div className="prose-sm space-y-8 text-ink-light leading-relaxed">
          <p className="text-xs text-ink-muted">Last updated: April 7, 2026</p>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              1. Agreement to Terms
            </h2>
            <p>
              By accessing or using StudyZone AI (&quot;the Service&quot;), you agree to be
              bound by these Terms of Service. If you do not agree to these terms, do not
              use the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              2. Description of Service
            </h2>
            <p>
              StudyZone AI is an AI-powered learning platform that allows users to upload
              study materials and receive guided, interactive learning experiences including
              lesson plans, quizzes, flashcards, summaries, and AI-powered tutoring.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              3. User Accounts
            </h2>
            <p>
              You are responsible for maintaining the confidentiality of your account
              credentials and for all activities that occur under your account. You must
              provide accurate and complete information when creating an account.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              4. Acceptable Use
            </h2>
            <p>You agree not to:</p>
            <ul className="ml-5 mt-2 list-disc space-y-1">
              <li>Upload content that you do not have the right to share</li>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to the Service</li>
              <li>Interfere with or disrupt the Service or its infrastructure</li>
              <li>Use the Service to generate harmful or misleading content</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              5. Intellectual Property
            </h2>
            <p>
              You retain ownership of all content you upload to the Service. By uploading
              content, you grant StudyZone AI a limited license to process and analyze your
              content solely for the purpose of providing the Service to you. We do not
              claim ownership of your uploaded materials.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              6. AI-Generated Content
            </h2>
            <p>
              Content generated by the AI (summaries, quizzes, explanations, etc.) is
              provided for educational purposes only. While we strive for accuracy, AI
              outputs may contain errors. You should verify important information
              independently.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              7. Fees and Payment
            </h2>
            <p>
              The Service offers both free and paid plans. Paid subscriptions are billed
              on a recurring basis. You may cancel your subscription at any time, and
              cancellation will take effect at the end of the current billing period.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              8. Limitation of Liability
            </h2>
            <p>
              The Service is provided &quot;as is&quot; without warranties of any kind. StudyZone
              AI shall not be liable for any indirect, incidental, special, or
              consequential damages arising from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              9. Termination
            </h2>
            <p>
              We reserve the right to suspend or terminate your access to the Service at
              any time for violation of these terms. Upon termination, your right to use
              the Service will immediately cease.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              10. Changes to Terms
            </h2>
            <p>
              We may update these terms from time to time. We will notify you of material
              changes by posting the updated terms on the Service. Your continued use after
              changes constitutes acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-lg font-semibold text-ink font-[family-name:var(--font-dm-sans)]">
              11. Contact
            </h2>
            <p>
              If you have questions about these terms, please contact us at{" "}
              <a href="mailto:hello@studyzoneai.com" className="text-ink underline">
                hello@studyzoneai.com
              </a>
              .
            </p>
          </section>
        </div>
    </main>
  );
}
